namespace educamlite
{
    [default_interface]
    runtimeclass PicItem : Windows.UI.Xaml.Controls.GridViewItem
    {
        PicItem(Windows.Storage.Streams.IRandomAccessStream picStream, UInt32 order);

        UInt32 Order{ get; set; };
        Windows.UI.Xaml.Media.Imaging.BitmapImage PicSource{ get; };

        void SetImageFrom(Windows.Storage.Streams.IRandomAccessStream picStream);
    }
}
